feat(ponder-ens): introduce plugin architecture
namehash/ens-multichain-indexer pull request #3
Opened 2024-12-31 06:14 UTC by tk-o

This change allows defining simple ponder plugins per supported ENS blockchain which can be loaded conditionally in the runtime.

Requesting a chain to be indexed requires passing a chain ID in the `CHAINS_TO_INDEX` env var and comma-separated chain ID values.

### Examples

#### Not using a supported chain ID

Results in no indexing handlers being loaded into the runtime, so ponder indexer has nothing to do:
```
CHAINS_TO_INDEX=11 DATABASE_SCHEMA=somechain pnpm start

> ens-multichain@0.0.1 start /Users/tko/dev/github/namehash/ens-multichain-indexer
> ponder start

7:11:03 AM INFO  build      Using PGlite database at .ponder/pglite (default)
7:11:03 AM ERROR build      Failed build
BuildError: Validation failed: Found 0 registered indexing functions.

7:11:03 AM WARN  process    Failed intial build, starting shutdown sequence
7:11:04 AM FATAL process    Finished shutdown sequence, terminating (exit code 1)
 ELIFECYCLE  Command failed with exit code 1.
```

#### Using a supported chain ID

Loads requested chain ENS plugin for ponder and starts indexing events.

```
CHAINS_TO_INDEX=1 DATABASE_SCHEMA=somechain pnpm start 

> ens-multichain@0.0.1 start /Users/tko/dev/github/namehash/ens-multichain-indexer
> ponder start

Indexing Ethereum ENS
7:11:12 AM INFO  build      Using PGlite database at .ponder/pglite (default)
7:11:12 AM INFO  database   Using database schema 'somechain'
7:11:12 AM INFO  database   Created tables [domains, accounts, resolvers, registrations]
7:11:13 AM INFO  historical Started syncing 'mainnet' with 4.1% cached
7:11:13 AM INFO  server     Started listening on port 42069
7:11:13 AM INFO  app        Indexed 1 events

2024-12-31 09:39 UTC, lightwalker-eth reviewed
@tk-o Hey thanks for all the efforts on this 🙌 Excited to see the "plugins" start to come to life! Will defer to @shrugs on more detailed review for the proposed plugin architecture.

A more general feedback from my side. For each PR we make, let's please also consider what documentation updates might be relevant and include them in the PR. Appreciate this takes time, but good documentation for other devs in the ENS community will be key to our success.

For example, ideas that would be great to include as documentation in the README.md with this PR might include:

1. Overall introduction and framing for what we're working to do here. For example: enable any permutation of chain-specific ENS indexers to be dynamically activated via environment variables.
2. Communicate known oversimplifications in our current approach and identify that our roadmap will remove these oversimplifications in time. For example:
   1. At the moment we're making oversimplifications where indexing "mainnet" represents indexing the legacy ENS Subgraph, indexing "base" represents only indexing subnames of "base.eth" on Base, and indexing "linea" represents only indexing subnames of "linea.eth" on Linea. Etc.
   2. At the moment we're making oversimplifications where we assume that all the delegation relationships of subname issuance from an L1 resolver (using ENSIP-10 and EIP-3668) to an offchain gateway server that reads state from a L2 subname registry is immutable. In other words, we're currently assuming that the current L2 subname registry for subnames of "base.eth" on Base is guaranteed to continue serving in that role.
4. Perhaps an .env.example file that includes comments documenting the environment variables we use and different example values that might be set. Am I correct to assume that there's also some ponder-related environment variables that we should be documenting in an .env.example file too? For example: RPC endpoints for different chains? Let's write our documentation under the assumption that the reader has never used Ponder before and should not need to familiarize themselves with Ponder if they just want to get started and run their own instance.
5. A "getting started" section that explains step-by-step how to go from cloning the repo to having a running instance of our indexer.
6. Any other ideas you suggest will be useful :+1: 😄

2025-01-02 19:08 UTC, tk-o commented on src/ponder-ens-plugins/ethereum/ponder.config.ts
> +    },
```suggestion
    Ethereum_RegistryOld: {
      network: "mainnet",
      abi: Registry,
      address: REGISTRY_OLD_ADDRESS,
      startBlock: 3327417,
      endBlock: END_BLOCK,
    },
    Ethereum_Registry: {
      network: "mainnet",
      abi: Registry,
      address: REGISTRY_ADDRESS,
      startBlock: 9380380,
      endBlock: END_BLOCK,
    },
    Ethereum_OldRegistryResolvers: {
      network: "mainnet",
      abi: RESOLVER_ABI,
      address: factory({
        address: REGISTRY_OLD_ADDRESS,
        event: getAbiItem({ abi: Registry, name: "NewResolver" }),
        parameter: "resolver",
      }),
      startBlock: 9380380,
      endBlock: END_BLOCK,
    },
    Ethereum_Resolver: {
      network: "mainnet",
      abi: RESOLVER_ABI,
      address: factory({
        address: REGISTRY_ADDRESS,
        event: getAbiItem({ abi: Registry, name: "NewResolver" }),
        parameter: "resolver",
      }),
      startBlock: 9380380,
      endBlock: END_BLOCK,
    },
    Ethereum_BaseRegistrar: {
      network: "mainnet",
      abi: BaseRegistrar,
      address: BASE_REGISTRAR_ADDRESS,
      startBlock: 9380410,
      endBlock: END_BLOCK,
    },
    Ethereum_EthRegistrarControllerOld: {
      network: "mainnet",
      abi: EthRegistrarControllerOld,
      address: ETH_REGISTRAR_CONTROLLER_OLD_ADDRESS,
      startBlock: 9380471,
      endBlock: END_BLOCK,
    },
    Ethereum_EthRegistrarController: {
      network: "mainnet",
      abi: EthRegistrarController,
      address: ETH_REGISTRAR_CONTROLLER_ADDRESS,
      startBlock: Math.min(16925618, END_BLOCK),
      endBlock: END_BLOCK,
    },
    Ethereum_NameWrapper: {
      network: "mainnet",
      abi: NameWrapper,
      address: NAME_WRAPPER_ADDRESS,
      startBlock: Math.min(16925608, END_BLOCK),
      endBlock: END_BLOCK,
    },
```

2025-01-02 19:16 UTC, tk-o commented on src/ponder-ens-plugins/ethereum/ponder.config.ts
> +    },
If we don't introduce any namespace, we'll have issues around types if the same contract name would rely on different set of arguments. I'd prefer merging contract definitions across chains in the v2 release.

2025-01-03 15:54 UTC, lightwalker-eth requested changes
@tk-o Hey nice updates! I like the direction you're moving in 🚀 Reviewed and shared feedback :+1:

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/main.ts
>      if (plugin.canActivate) {
Small feedback: maybe we should rename `canActivate` to `shouldActivate`.

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/base/ponder.config.ts
> +      startBlock: 9380410,
Should we define a named constant for this?

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/base/ponder.config.ts
> +    mainnet: {
Interesting, so the base indexer also makes use of mainnet RPC calls?

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/chain.ts
> +  if (!process.env.ENS_DEPLOYMENT_CHAIN_ID) {
Perhaps we should rename the `ENS_DEPLOYMENT_CHAIN_ID` variable so it is more self documenting?

For example, as I understand this environment variable is currently used to identify what chain id should have its indexing activated on. In my mind this is a different idea than an "ENS deployment chain id" because currently there's only an ENS deployment to mainnet and sepolia.

It can be helpful to separate the idea of ENS from any particular TLD such as ".eth" or any particular subname. ENS is rooted in overall ENS root which lives only on mainnet (and a testnet deployment on sepolia).

One quick alternative idea is to call it `INDEXED_CHAIN_ID` -- open to other ideas too 😄

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/chain.ts
> +export function createNs<ChainId extends number>(chainId: ChainId) {
My understanding is that this is a utility function to help with namespacing?

Suggest we define our namespacing based on ENS names, not on chain ids. It's true that we are applying a simplifying assumption right now that mainnet => direct subnames of .eth and base => direct subnames of base.eth. I'm happy with this simplifying assumption, but prefer where possible we try to avoid leaning into this too hard.

Would it add much scope to make it so that each of our plugins included not only a defined chain id, but also a defined ENS name of direct subnames the plugin takes responsibility for indexing? For example, our mainnet plugin would set this config to "eth" and our base plugin would set this config to "base.eth".

Please let me know if any concerns or questions :+1:

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/base/README.md
> +# Base ENS plugin for Ponder indexer
Suggest we rename all references to this plugin from "base" to "base.eth".

Suggest we have a mindset that the fundamental way we refer to plugins is through ENS names and not chains.

The following is an open task for after we finish our V1. Suggest we only follow up on this later. Please also add a task to the root README as a pending action item for V2+:

* Separate the "ethereum" plugin into two separate items:
   * "Root" ENS contracts, which are not specific to the "eth" TLD. The ENS name associated with these should be "" (empty string, representing the ENS root).
   * "eth" TLD contracts, which should be separated into a plugin for the ENS name "eth".

2025-01-03 15:54 UTC, lightwalker-eth commented on src/ponder-ens-plugins/base/README.md
> +The Base implementation for ENS protocol has custom naming convention, which was described here:
Very happy to see this documentation here! Here's some suggestions for details in the language we use:

1. We shouldn't refer to this as "The Base implementation for ENS protocol". This plugin is for indexing subnames of "base.eth". It just so happens that the related contracts are on Base today, but in theory that might change in the future. We should think of plugins based on ENS names, not on chains.
2. We shouldn't use the language "... has custom naming convention". In the ENS community, "naming convention" might mean different things to different people. Suggest instead we use more specific ENS terminology. For example: "The `base.eth` subname registrar / registry is similar to the `eth` subname registrar with a few customizations as described here:"

2025-01-03 15:54 UTC, lightwalker-eth commented on src/lib/ens-helpers.ts
> +export const NAMEHASH_BASE_ETH = namehash("base.eth");
In ENS terminology, "namehash" is a function and the value returned by that function is referred to as a "node". Therefore, suggest renaming each of these constants to be prefixed with "NODE_" instead of "NAMEHASH_"

2025-01-03 15:54 UTC, lightwalker-eth commented on src/lib/ens-helpers.ts
>  export const NAMEHASH_ZERO = namehash("");
In ENS terminology, this might be referred to as "NODE_ROOT". It's true that this is a bunch of zeros, but more symbolically it represents the root node in ENS.

2025-01-03 17:23 UTC, shrugs reviewed
an abi diff between mainnet and base would be helpful for identifying any logic discrepancies

please configure your editor to use biome to format files — the columnWidth being changed from 80 to 100 is causing a lot of formatting-related changes

2025-01-03 17:23 UTC, shrugs commented on ponder.config.ts
>  export default createConfig({
feels like this should be `createConfigWithPlugins([basePlugin, ethereumPlugin])` which does some similar logic, chuck it and all of the other plugin stuff into a `lib/plugins.ts`

2025-01-03 17:23 UTC, shrugs commented on src/lib/ens-helpers.ts
> +export const NAMEHASH_BASE_ETH = namehash("base.eth");
noted, this was inherited from my code — was originally called NODE_, will revert 👍

2025-01-03 17:23 UTC, shrugs commented on src/ponder-ens-plugins/base/handlers/Resolver.ts
> +export function initResolverHandlers() {
instead of exporting an object, let's just export a default function like

`export default function () { ... }`

and in ponder.indexing you can just call the default export of these modules to attach the handlers.

2025-01-03 17:23 UTC, shrugs commented on src/ponder-ens-plugins/base/ponder.config.ts
> +export const config = Object.freeze({
here's what i'm looking at for the plugin interface, very simple:

`base/ponder.plugin.ts`

```
export default function createPlugin(): PonderPluginConfig {
  return Object.freeze({ // Object.freeze only if necessary, maybe can use `as const` at the end?
    networks: { ... }
    contracts: {
      [...]: {
         // existing config...
       }
    },
    activate() {
      // ... the logic from ponder.indexing.ts
    }
  })
}
```

and then a 

```ts
function createConfigWithPlugins(plugins: PonderPluginConfig, contractOptions: Pick<ContractConfig, "startBlock" | "endBlock">) {
  return createConfig({
    // merge networks from each plugin
    networks: { ... }
    // merge contracts from each plugin, including contractOptions, so start/end blocks are configured at the top level
  })
}
```

also we're only ever running a single plugin at once so all of the logic here could just accept a single plugin instead of an array

then in the main ponder.config.ts that ponder loads simply run:

```
const plugins = [ethereumPlugin, basePlugin].filter((plugin) => ... )
export default createConfigWithPlugins(plugins, { endBlock: 12_000_000 })
```

2025-01-03 17:23 UTC, shrugs commented on src/ponder-ens-plugins/base/ponder.config.ts
> +const REGISTRY_ADDRESS = '0xb94704422c2a1e396835a571837aa5ae53285a95';
i didn't do this in the original config but now i'd suggest just inlining all of these config variables in each of the plugins — defining variables for each of these seems verbose and unnecessary

2025-01-03 19:47 UTC, shrugs commented on src/ponder-ens-plugins/base/ponder.config.ts
> +export const config = Object.freeze({
actually i'm realize the endblock stuff doesn't make a lot of sense at the moment, as those are chain-specific and also not important to implement, so please ignore this comment in favor of what i've proposed in #4

2025-01-03 21:38 UTC, tk-o commented on src/ponder-ens-plugins/base/ponder.config.ts
> +const REGISTRY_ADDRESS = '0xb94704422c2a1e396835a571837aa5ae53285a95';
Makes sense, these are not used outside of the config object.

2025-01-04 17:19 UTC, shrugs commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +      address: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
ah sorry — if it's an address that's re-used for a factory config or used more than once we should keep it in a constant so that the reader knows that it's guaranteed to be identical 😅  — sorry i was not specific originally

2025-01-06 11:10 UTC, tk-o commented on src/ponder-ens-plugins/base/ponder.config.ts
> +      startBlock: 9380410,
I discussed with @shrugs to inline the config params that are not used outside the config file. Reading the config file should be a good start to understanding which contract is indexed with what params. What do you think?

2025-01-06 11:13 UTC, tk-o commented on src/ponder-ens-plugins/chain.ts
> +  if (!process.env.ENS_DEPLOYMENT_CHAIN_ID) {
Updated the env var to `INDEX_BASENAME` where the expected values are among `.eth`, `.base.eth`, `.linea.eth`. In short, the value format requires a dot at the beginning and an `eth` at the end.

2025-01-06 11:15 UTC, tk-o commented on src/ponder-ens-plugins/chain.ts
> +export function createNs<ChainId extends number>(chainId: ChainId) {
Using namespaces is needed for correct ponder app build. Ponder flattens all contracts configured across our ponder ens plugins, which causes type conflicts. Namespaces resolve that issue.

2025-01-06 11:19 UTC, tk-o commented on src/lib/ens-helpers.ts
> +export const NAMEHASH_BASE_ETH = namehash("base.eth");
Updated

2025-01-06 11:19 UTC, tk-o commented on src/ponder-ens-plugins/base/README.md
> +The Base implementation for ENS protocol has custom naming convention, which was described here:
Updated

2025-01-06 11:19 UTC, tk-o commented on src/lib/ens-helpers.ts
>  export const NAMEHASH_ZERO = namehash("");
Updated

2025-01-06 11:19 UTC, tk-o commented on src/ponder-ens-plugins/base/README.md
> +# Base ENS plugin for Ponder indexer
Updated

2025-01-06 11:21 UTC, tk-o commented on src/ponder-ens-plugins/main.ts
>      if (plugin.canActivate) {
We dropped the activation getter and simply check the value of the `INDEX_BASENAME` env var

2025-01-06 12:42 UTC, lightwalker-eth requested changes
@tk-o Hey great to see the updates here. 👍  Reviewed and shared feedback 😄

2025-01-06 12:42 UTC, lightwalker-eth commented on src/handlers/Registry.ts
> +export async function setup({ context }: { context: Context }) {
Can we please document the big idea behind this function? For example: What purpose does it solve? What is the bigger theory behind why it exists?

For example, I'm assuming this function has the responsibility to initialize the indexed state of the registry? Assuming so, can we please document this idea? If that's incorrect, no worries, whatever the correct idea is, let's please document it :+1:

2025-01-06 12:42 UTC, lightwalker-eth commented on src/handlers/Registry.ts
> +type NsType<T extends string> = NsReturnType<T, "/eth">;
Let's please document the thinking here. Thanks

2025-01-06 12:42 UTC, lightwalker-eth commented on src/handlers/Registry.ts
> +  // ensure we have a root Domain, owned by the zeroAddress, that is default not migrated
```suggestion
  // initialize the ENS root to be owned by the zeroAddress and not migrated
```

2025-01-06 12:42 UTC, lightwalker-eth commented on src/handlers/Resolver.ts
> +type NsType<T extends string> = NsReturnType<T, "/eth">;
Can we please add a comment here explaining the thinking?

2025-01-06 12:42 UTC, lightwalker-eth commented on src/lib/plugins.ts
> +// TODO: change the chainId to the root node value (i.e. namehash("base.eth"))
Should we update this comment? It looks like it might be old?

2025-01-06 12:42 UTC, lightwalker-eth commented on src/lib/plugins.ts
> +export type NsReturnType<
```suggestion
export type NsContractName<
```

Just a suggestion. Let me know what you think.

2025-01-06 12:42 UTC, lightwalker-eth commented on src/lib/plugins.ts
> +export const EnsRootDomains = ["/eth", "/eth/base"] as const;
```suggestion
export const EnsIndexedDomains = ["/eth", "/eth/base"] as const;
```

Just a suggestion. Let me know what you think.

2025-01-06 12:42 UTC, lightwalker-eth commented on src/lib/plugins.ts
> +export type EnsRootDomain = (typeof EnsRootDomains)[number];
```suggestion
export type EnsIndexedDomain = (typeof EnsIndexedDomains)[number];
```

Just a suggestion. Let me know what you think.

2025-01-06 12:42 UTC, lightwalker-eth commented on .env.local.example
> +INDEX_BASENAME=.base.eth
```suggestion
INDEX_SUBNAMES=base.eth
```

Two suggestions here:

1. Rename `INDEX_BASENAME` to `INDEX_SUBNAMES`: "subnames" is more common language in ENS and "base" already has multiple potential interpretations in our project.
2. Don't prefix the value with "." In other words, make it "base.eth" instead of ".base.eth". This way the value is a valid ENS name.

2025-01-06 12:42 UTC, lightwalker-eth commented on .env.local.example
> +# ponder indexer ens deployment configuration
```suggestion
# Identify which ENS indexer plugin to activate.
```

Can we please add more docs here? For example? Does this value always need to be a single value, or can it be multiple values? If it can be multiple values, how to format it? It can also be nice to document which values are supported here or perhaps in the overall README.md.

2025-01-06 12:42 UTC, lightwalker-eth commented on .env.local.example
> +DATABASE_SCHEMA=ponder_ens_base.eth
Can you please document more details about how this `DATABASE_SCHEMA` should be set? Please also explain how this value might relate to the `INDEX_SUBNAMES` environment variable.

2025-01-06 12:42 UTC, lightwalker-eth commented on .env.local.example
> +## one schema name per chain ID, i.e. ponder_ens_${INDEX_BASENAME}
This comment seems old and no longer relevant? Can we please review & update? Thanks!

2025-01-06 12:42 UTC, lightwalker-eth commented on ponder.config.ts
> +      throw new Error(`Unsupported base name: ${BASENAME}`);
```suggestion
      throw new Error(`Unsupported subname indexer: ${BASENAME}`);
```

2025-01-06 12:42 UTC, lightwalker-eth commented on ponder.config.ts
> +  config as ethereumConfig
```suggestion
  config as ethConfig
```

2025-01-06 12:42 UTC, lightwalker-eth commented on src/lib/ens-helpers.ts
> +class BaseName {
Can you please document what the goals are for this? It will help me to review and share advice :+1:

2025-01-06 12:42 UTC, lightwalker-eth commented on src/handlers/Registrar.ts
> +type NsType<T extends string> = NsReturnType<T, "/eth">;
Can we please document the idea here?

2025-01-06 12:42 UTC, lightwalker-eth commented on src/handlers/Registrar.ts
> +export const makeRegistryHandlers = (baseName: `.${`${string}`}eth`) => {
Can we please document the idea here? I'm having difficulty reviewing and sharing feedback. Thanks

2025-01-06 12:42 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +export const baseName = ".eth" as const;
Please see my other feedback on this:

1. We shouldn't prefix with "."
2. The ENS community doesn't use language such as "baseName". We should discuss what language would be better.
3. In this context, I assume we should just be calling this "indexedSubnames"?

2025-01-06 12:42 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +export type NsType<T extends string> = NsReturnType<T, typeof nestedNamespace>;
We need to document what each of these lines are doing. It's not clear when reviewing the code. Cheers thanks

2025-01-06 12:42 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export const baseName = ".base.eth" as const;
Please see my comments on this from other files :+1:

2025-01-06 12:42 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export type NsType<T extends string> = NsReturnType<T, typeof nestedNamespace>;
We need to document each of these ideas. They aren't intuitive for others when reviewing the code.

2025-01-06 12:42 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +const START_BLOCK = undefined; // 17607350;
Can we please document the idea here? Why setting these to undefined?

2025-01-06 13:02 UTC, tk-o commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +export const baseName = ".eth" as const;
`IndexedSubname` works for me 👍

2025-01-06 19:32 UTC, shrugs commented
i much prefer the `root` argument passed to `makeRegistryHandlers()` because it makes clear that the registry handlers are universal except for root that nodes in those handlers are relative to. it also means that in the future v2 this shared code should be relatively identical. using the constant is less clear and requires more mental overhead for the reader

2025-01-07 19:57 UTC, shrugs reviewed
excellent documentation & typescript type work! i only have nitpicks in here, i think, so it's looking very close to merge

2025-01-07 19:57 UTC, shrugs commented on src/handlers/Registrar.ts
> +export const makeRegistryHandlers = (indexedSubname: `${string}eth`) => {
now that i understand the nomenclature better, let's call this `indexedSubname` variable `managedSubname` (and `managedSubnameNode`) so that people know that these Registrar handlers are in the context of a registrar that manages the provided subname

2025-01-07 19:57 UTC, shrugs commented on src/handlers/Registrar.ts
> +    get indexedSubnameNode() {
why provide this back, it will be known to the caller because they provided it as an input agument

2025-01-07 19:57 UTC, shrugs commented on src/handlers/Registrar.ts
> +        block: { timestamp: bigint };
i agree on splitting out the args for clarity, but can you type the block argument as a ponder `Block`?

2025-01-07 19:57 UTC, shrugs commented on src/handlers/Registrar.ts
> +      args: {
and i think for each of these functions in `Registrar.ts` we should standardize the api to be like a ponder handler: it always accepts context and event, and `args` is within the event. we need not do this in this pr, i can manage it once we've merged if you'd like

2025-01-07 19:57 UTC, shrugs commented on src/handlers/Registry.ts
> +export async function handleRootNodeCreation({ context }: { context: Context }) {
agreed with lightwalker's naming concern, and apologies for the nitpick, but how about calling this `setupRootNode`

2025-01-07 19:57 UTC, shrugs commented on src/handlers/Resolver.ts
> -type NsType<T extends string> = NsReturnType<T, "/eth">;
very nice

2025-01-07 19:57 UTC, shrugs commented on src/lib/ponder-plugin-utils.ts
> +type EthSubname = `${string}eth`;
very nice type work in this file 🫡

2025-01-07 22:14 UTC, tk-o commented on src/handlers/Registrar.ts
> +    get indexedSubnameNode() {
We need this value in the caller for some inline indexing handlers:
https://github.com/namehash/ens-multichain-indexer/blob/aad651cf532f1d89b214695994bb2d8e2574b7e3/src/ponder-ens-plugins/eth.base/handlers/Registrar.ts#L8-L17
https://github.com/namehash/ens-multichain-indexer/blob/aad651cf532f1d89b214695994bb2d8e2574b7e3/src/ponder-ens-plugins/eth.base/handlers/Registrar.ts#L31

2025-01-07 22:28 UTC, shrugs commented
looks like biome got misconfigured or something — some line width formatting related changes in the recent commits

2025-01-08 12:24 UTC, lightwalker-eth requested changes
@tk-o Thanks for your updates here! Very happy to see docs improving. Let's continue to push hard on making our docs and use of language properly aligned.

Reviewed and shared feedback :+1:

2025-01-08 12:24 UTC, lightwalker-eth commented on .env.local.example
> +# ponder indexer ens deployment configuration
@tk-o This is still an open feedback

2025-01-08 12:24 UTC, lightwalker-eth commented on .env.local.example
> +DATABASE_SCHEMA=ponder_ens_base.eth
@tk-o This remains an open feedback item.

I'm also concerned to read "chain id" here. I'm very worried we're getting key ideas confused. In my understanding, "chain id" should not be THE key consideration in our configurations. The `INDEX_SUBNAME` should be THE number 1 consideration, and then everything else should flow downstream from that.

For example, the chain to index is determined by the subnames to be indexed. Not the other way around.

2025-01-08 12:24 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export const managedSubname = "base.eth" as const;
Could you help me understand the use of the word "managed" here? Is there a special reason to use that and not "indexed"?

What does it mean to be "managed"?

2025-01-08 12:24 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export const ponderNamespace = createPonderNamespace(managedSubname);
Is there a special reason for us to put lots of emphasis on "ponder" when we name things?

It's true that we're building on the Ponder framework, but I feel attracted to more general naming of these ideas. For example:

* "ponderNamespace" -> "pluginNamespace"
* "createPonderNamespace" -> "createPluginNamespace"

Very open to other suggestions. Perhaps I'm missing something?

2025-01-08 12:24 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +export const managedSubname = "eth";
Please see my other comment about the use of the word "managed" here.

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ens-helpers.ts
> +    if (!name.endsWith("eth")) throw new Error(`ManagedSubname should end with 'eth'`);
Could we please add a comment here that in the future we'll be working to make enhancements to support any TLD, not just "eth".

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ens-helpers.ts
> +class ManagedSubname {
Could we please add comments describing the goal / responsibility of this class?

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ens-helpers.ts
> +export const INDEXED_SUBNAME = ManagedSubname.parse(process.env.INDEX_SUBNAME).toString();
Can we please add comments with lots of details about `INDEXED_SUBNAME`?

1. What are the goals of this field? What idea does it represent?
2. What are the constraints on the value of this field?

2025-01-08 12:24 UTC, lightwalker-eth commented on src/handlers/Registrar.ts
> +    get managedSubnameNode() {
Please see other comments I've shared about using the word "managed" vs. "indexed"

2025-01-08 12:24 UTC, lightwalker-eth commented on src/handlers/Registrar.ts
> +  const managedSubnameNode = namehash(managedSubname);
Please see other comments I've shared about using the word "managed" vs. "indexed"

2025-01-08 12:24 UTC, lightwalker-eth commented on src/handlers/Registrar.ts
> + * A factory function that returns Ponder indexing handlers for a specified index name/subname.
```suggestion
 * A factory function that returns Ponder indexing handlers for a specified subname.
```

2025-01-08 12:24 UTC, lightwalker-eth commented on ponder.config.ts
> +      throw new Error(`Unsupported base name: ${INDEXED_SUBNAME}`);
```suggestion
      throw new Error(`Unsupported INDEXED_SUBNAME: ${INDEXED_SUBNAME}`);
```

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ponder-plugin-utils.ts
> + * Transforms a domain name into a path-like format
Happy to see this comment here!

Can we please also document why we created this function? Anytime we write a function that has a non-obvious purpose we should be documenting why it exists.

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ponder-plugin-utils.ts
> +function transformDomain<T extends string>(domain: T): TransformDomain<T> {
```suggestion
function nameToPath<T extends string>(name: T): NamePath<T> {
```

1. The param we're passing in is a name, not a domain.
2. We should be more specific in the transformation being made. Ex: `nameToPath`.
3. We should be more specific in what the result is. Ex: `NamePath`.

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ponder-plugin-utils.ts
> +type EthSubname = `${string}eth`;
@tk-o Yeah nice work here! 💪

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ponder-plugin-utils.ts
> +  /** Creates a name-spaced contract name */
```suggestion
  /** Creates a namespaced contract name */
```

namespace / namespaced is one word, no hyphen.

Please search for other instances of "name-spaced" and replace them. Thanks.

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ponder-plugin-utils.ts
> + * Let's say we have two contracts named `Registry`. One handles the `eth` name, and the other handles the `base.eth` subname. We need to create a name-spaced contract name to avoid conflicts.
```suggestion
 * Let's say we have two contracts named `Registry`. One handles `eth` subnames, and the other handles `base.eth` subnames. We need to create a namespaced contract name to avoid conflicts.
```

2025-01-08 12:24 UTC, lightwalker-eth commented on src/lib/ponder-plugin-utils.ts
> +/**
@tk-o Great job on the docs here! 🚀 🚀 This makes a big impact for our goals! Docs like this do a lot to help encourage other devs to adopt our indexer because they can more easily make sense of what we're doing and why 😄 

One small suggestion is to break to a new line around approximately 80ish characters. This helps with line wrapping when viewing code on platforms such as GitHub.

2025-01-08 12:24 UTC, lightwalker-eth commented on src/ponder-ens-plugins/eth.base/handlers/Registrar.ts
What do you think about renaming the `ponder-ens-plugins` directory to just `plugins`? Seems more clean 😄 

Assuming we do rename, please be sure to do it in the way that it's properly tracked by git as just renames, and not a bunch of file deletes / creations.

2025-01-08 12:24 UTC, lightwalker-eth commented on .github/workflows/static-analysis.yml
> +name: Static Analysis
Great to see this!

2025-01-08 14:37 UTC, tk-o commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export const managedSubname = "base.eth" as const;
@shrugs could you share your view here?

2025-01-08 14:40 UTC, tk-o commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +export const managedSubname = "eth";
cc @shrugs

2025-01-08 15:15 UTC, tk-o commented on src/ponder-ens-plugins/eth/ponder.config.ts
> +export const managedSubname = "eth";
I've reverted back to `indexedSubname`

2025-01-08 15:59 UTC, shrugs commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export const ponderNamespace = createPonderNamespace(managedSubname);
I might suggest `contractNamespace`

2025-01-08 16:00 UTC, shrugs commented on src/ponder-ens-plugins/eth.base/ponder.config.ts
> +export const managedSubname = "base.eth" as const;
@lightwalker-eth it got lost in the github comments but: the registrar handlers are in the context of the subname that the registrar 'manages' — the ETH Registrar manages .eth, base's l2 registrar deployment manages .base.eth subnames, etc. perhaps there's a better word but i don't like 'indexed' in this case, since the argument is specifying which parent node all of the events in this registrar are relative to

2025-01-08 16:12 UTC, shrugs commented on src/handlers/Registrar.ts
> +    get indexedSubnameNode() {
ah, hmm. i don't love this but it's ok for the moment 👍  we'll refactor this in v2

2025-01-08 16:29 UTC, lightwalker-eth approved these changes
@tk-o Hey super awesome updates! 🚀 🚀 🚀

2025-01-08 16:33 UTC, merged